INSERT INTO t_USER (C_USERNAME, C_PASSWORD) VALUES ('BOHLOULI', '3459150');
INSERT INTO t_USER (C_USERNAME, C_PASSWORD) VALUES ('USER', '123456');
INSERT INTO T_AUTH_USER_GROUP(C_USERNAME, C_AUTH_GROUP) VALUES ( 'USER','ADMIN' );
INSERT INTO T_AUTH_USER_GROUP(C_USERNAME, C_AUTH_GROUP) VALUES ( 'BOHLOULI','USER' );