CREATE TABLE t_User (
    c_USER_Id BIGINT AUTO_INCREMENT PRIMARY KEY,
    c_USERNAME VARCHAR(128) NOT NULL UNIQUE,
    c_PASSWORD VARCHAR(256) NOT NULL
);

CREATE TABLE t_AUTH_USER_GROUP (
    c_AUTH_USER_GROUP_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    c_USERNAME VARCHAR(128) NOT NULL,
    c_AUTH_GROUP VARCHAR(128) NOT NULL,
    CONSTRAINT c_USER_AUTH_USER_GROUP_FK FOREIGN KEY (c_USERNAME) REFERENCES t_AUTH_USER_GROUP
)